// This file will be generated by Supabase CLI
// For now, we'll define a basic structure

export interface Database {
  public: {
    Tables: {
      businesses: {
        Row: {
          id: string;
          name: string;
          description: string | null;
          logo_url: string | null;
          google_business_url: string | null;
          phone: string | null;
          email: string | null;
          address: string | null;
          website: string | null;
          brand_color: string | null;
          welcome_message: string | null;
          thank_you_message: string | null;
          user_id: string;
          created_at: string;
          updated_at: string;
        };
        Insert: {
          id?: string;
          name: string;
          description?: string | null;
          logo_url?: string | null;
          google_business_url?: string | null;
          phone?: string | null;
          email?: string | null;
          address?: string | null;
          website?: string | null;
          brand_color?: string | null;
          welcome_message?: string | null;
          thank_you_message?: string | null;
          user_id: string;
          created_at?: string;
          updated_at?: string;
        };
        Update: {
          id?: string;
          name?: string;
          description?: string | null;
          logo_url?: string | null;
          google_business_url?: string | null;
          phone?: string | null;
          email?: string | null;
          address?: string | null;
          website?: string | null;
          brand_color?: string | null;
          welcome_message?: string | null;
          thank_you_message?: string | null;
          user_id?: string;
          created_at?: string;
          updated_at?: string;
        };
      };
      reviews: {
        Row: {
          id: string;
          business_id: string;
          customer_name: string;
          customer_phone: string | null;
          rating: number;
          comment: string | null;
          is_public: boolean;
          created_at: string;
          updated_at: string;
        };
        Insert: {
          id?: string;
          business_id: string;
          customer_name: string;
          customer_phone?: string | null;
          rating: number;
          comment?: string | null;
          is_public?: boolean;
          created_at?: string;
          updated_at?: string;
        };
        Update: {
          id?: string;
          business_id?: string;
          customer_name?: string;
          customer_phone?: string | null;
          rating?: number;
          comment?: string | null;
          is_public?: boolean;
          created_at?: string;
          updated_at?: string;
        };
      };
      analytics: {
        Row: {
          id: string;
          business_id: string;
          metric_type: string;
          value: number;
          metadata: Record<string, unknown> | null;
          created_at: string;
        };
        Insert: {
          id?: string;
          business_id: string;
          metric_type: string;
          value: number;
          metadata?: Record<string, unknown> | null;
          created_at?: string;
        };
        Update: {
          id?: string;
          business_id?: string;
          metric_type?: string;
          value?: number;
          metadata?: Record<string, unknown> | null;
          created_at?: string;
        };
      };
    };
    Views: {
      [key: string]: never;
    };
    Functions: {
      [key: string]: never;
    };
    Enums: {
      [key: string]: never;
    };
  };
}
